### ISSUE TITLE
Possible Speedup

### ISSUE THREAD

**Issue by eladmw** [li-plus/seam-carving#1]
This library is not as fast as preferred, so I have a suggestion. you could use numba or jit to speedup your functions, I'll make my own version and submit a pull request soon.

**Comment by li-plus** [comment]
It is definitely possible. Any pull request is welcome!

**Comment by li-plus** [comment]
Thanks for your advice. I have implemented an accelerated version using numba jit and gained a 4x end-to-end speedup for forward energy and 2x for backward energy (#4). You may try out the new version `seam-carving==1.1.0` for further speedup.

Closing this issue. Feel free to re-open it if you got any problem.
